---
- name: create etcd group
  become: yes
  become_user: root
  group:
    name: '{{etcd_group}}'
    state: present
  
- name: create etcd user
  become: yes
  become_user: root
  user:
    name: '{{etcd_user}}'
    group: '{{etcd_group}}'
    home: '{{etcd_data_dir}}'
    state: present

- name: create dirs...
  become: yes
  become_user: root
  file:
    state: directory
    path: '{{item}}'
    owner: '{{etcd_user}}'
    group: '{{etcd_group}}'
    mode: 0755
  with_items:
    - /etc/etcd
    - '{{etcd_cluster_pki_dir}}'
    
- include: pki.yml
  when: etcd_secure

- name: install etcd.service configuration
  become: yes
  become_user: '{{etcd_user}}'
  with_items:
    - etc/etcd/etcd.conf
  template:
    src: '{{item}}.j2'
    dest: /{{item}}
    mode: 0644

- include: '{{etcd_init_system}}.yml'
